const threads = [
  {
    id: 'thread-dashboard',
    title: 'Build threads dashboard',
    preview: 'Create an active-thread dashboard embedded directly inside Codex.',
    projectName: 'Codex Dashboard',
    projectPath: '/Users/lawrenceawe/Codex Dashboard',
    recencyEpochMillis: Date.now() - 3_000,
    isPinned: true,
    model: 'gpt-5.6-sol',
    runState: 'running',
    workingTreeStatus: 'hasChanges',
  },
  {
    id: 'thread-review',
    title: 'Review project for bugs',
    preview: 'Inspect the project for correctness problems and produce actionable findings.',
    projectName: 'voice-tiktok-scroller',
    projectPath: '/Users/lawrenceawe/voice-tiktok-scroller',
    recencyEpochMillis: Date.now() - 780_000,
    isPinned: false,
    model: 'gpt-5.6-terra',
    runState: 'idle',
    workingTreeStatus: 'clean',
  },
  {
    id: 'thread-idle',
    title: 'Fix back command detection',
    preview: 'Improve recognition of the spoken back command.',
    projectName: 'voice-tiktok-scroller',
    projectPath: '/Users/lawrenceawe/voice-tiktok-scroller',
    recencyEpochMillis: Date.now() - 86_400_000,
    isPinned: false,
    model: 'gpt-5.6-terra',
    runState: 'idle',
    workingTreeStatus: 'clean',
  },
];
window.__codexDashboard.applyThreads(threads);
window.__codexDashboard.open();
