const threads = [
  {
    id: 'thread-dashboard',
    title: 'Build threads dashboard',
    preview: 'Create an active-thread dashboard embedded directly inside Codex.',
    projectName: 'Codex Dashboard',
    checkoutPath: '/Users/example/Codex Dashboard',
    projectID: 'dashboard',
    projectGroupPath: '/Users/example/Codex Dashboard',
    recencyEpochMillis: Date.now() - 3_000,
    isPinned: true,
    isUnread: true,
    latestLifecycleEventKind: 'started',
    model: 'gpt-6.1-sol',
    runState: 'running',
    projectGitStatus: 'uncommittedChanges',
    sharesProjectRepository: true,
  },
  {
    id: 'thread-review',
    title: 'Review project for bugs',
    preview: 'Inspect the project for correctness problems and produce actionable findings.',
    projectName: 'voice-tiktok-scroller',
    checkoutPath: '/Users/example/voice-tiktok-scroller',
    projectID: 'voice-tiktok-scroller',
    projectGroupPath: '/Users/example/voice-tiktok-scroller',
    recencyEpochMillis: Date.now() - 780_000,
    isPinned: false,
    isUnread: false,
    latestLifecycleEventKind: 'completed',
    model: 'gpt-6-luna',
    runState: 'idle',
    projectGitStatus: 'clean',
    sharesProjectRepository: true,
  },
  {
    id: 'thread-idle',
    title: 'Fix back command detection',
    preview: 'Improve recognition of the spoken back command.',
    projectName: 'voice-tiktok-scroller',
    checkoutPath: '/Users/example/voice-tiktok-scroller',
    projectID: 'voice-tiktok-scroller',
    projectGroupPath: '/Users/example/voice-tiktok-scroller',
    recencyEpochMillis: Date.now() - 86_400_000,
    isPinned: false,
    isUnread: false,
    latestLifecycleEventKind: 'completed',
    model: 'gpt-5.6-terra',
    runState: 'idle',
    projectGitStatus: 'clean',
    sharesProjectRepository: true,
  },
];
window.__codexDashboard.applyThreads(threads);
window.__codexDashboard.openChatOverview();
